---
title: "R Day 8 exercises"
author: "Peixuan Huang"
date: "`r Sys.Date()`"
output: html_document
---

```{r global_options, echo = FALSE, include = FALSE}
knitr::opts_chunk$set(echo=answers, eval=answers,
                      warning = FALSE, message = FALSE,
                      cache = FALSE, tidy = FALSE)
```



## Task 1

```{r}
library(here)

schools <- read.csv(here::here("data/nys_schools.csv"))
counties <- read.csv(here::here("data/nys_acs.csv"))
```


## Task 2

```{r}
summary(schools)
summary(counties)

length(unique(schools$school_name))
length(unique(counties$county_name))

table(schools$county_name)
table(schools$year)
table(counties$year)

```


## Task 3

1. Since no reasonable replacement values for -99, replace them with NA and drop these rows.

2. Use the 1st and 3rd Q as criteria for "low, medium, high"

```{r}
library(dplyr)

schools[schools == -99] <- NA
counties[counties == -99] <- NA
schools <- na.omit(schools)
counties <- na.omit(counties)

summary(counties$county_per_poverty)

counties$poverty_grp <- "medium"
counties$poverty_grp[counties$county_per_poverty <= 0.10903] <- "low"
counties$poverty_grp[counties$county_per_poverty > 0.14929] <- "high"

schools <- schools %>% group_by(year) %>% mutate(., scaled_mean_ela = scale(mean_ela_score))
schools <- schools %>% group_by(year) %>% mutate(., scaled_mean_math = scale(mean_math_score))

```


## Task 4

```{r}
county_level <- merge(schools, counties, by = c("county_name", "year"), all.x = T, all.y = T)

county_level <- na.omit(county_level)
```


## Task 5

```{r}
county_level %>% 
  group_by(county_name) %>% 
  summarize(total_enroll = sum(total_enroll), per_lunch = mean(per_free_lunch+per_reduced_lunch), per_poverty = mean(county_per_poverty))

county_level %>%
  group_by(county_name) %>%
  summarize(total_enroll = sum(total_enroll), per_lunch = mean(per_free_lunch+per_reduced_lunch), per_poverty = mean(county_per_poverty)) %>%
  arrange(.,per_poverty) %>%
  slice(., 62:58, 1:5)
```
## Task 6

```{r}
library(tidyverse)

ggplot(schools, mapping = aes(x = per_free_lunch+per_reduced_lunch, y = scaled_mean_math+scaled_mean_ela)) +
  geom_point() +
  geom_smooth() +
  labs(title = "Relationship between percentage of lunches and testing scores", 
       x = "Lunch percentage", y = "Testing scores")

county_level %>% 
  group_by(poverty_grp, county_name) %>% 
  summarise(output=mean(scaled_mean_math + scaled_mean_ela)) %>% 
  ggplot() + 
  geom_col(aes(x=poverty_grp, y=output, group=county_name), position="dodge") + 
  labs(title="Testing across counties for different poverty groups", x="Poverty groups", y="Testing performance")
```

## Task 7

```{r}
county_level %>% 
  group_by(poverty_grp, year) %>% 
  summarise(output=mean(scaled_mean_math + scaled_mean_ela)) %>% 
  ggplot() + 
  geom_line(aes(x=year, y=output, group=poverty_grp, col=poverty_grp), size = 1) + 
  labs(title="Testing for different poverty groups over the years", x="Year", y="Testing performance")


```